networks:
  pac-network:
    driver: bridge
services:
  pac-authentication:
    build:
      context: "./src/authentication"
    container_name: "pac-authentication"
    ports:
      - "8001:8001"
    env_file:
      - ./envs/.env.test
    command: ["fastapi", "run", "./app/Authentication.py", "--port", "8001"]
    networks:
      - pac-network
  tester:
    build:
      context: "./tests/unit_tests"
    container_name: "tester"
    env_file:
      - ./envs/.env.test
    networks:
      - pac-network
    depends_on:
      - pac-authentication
