networks:
  pac-network:
    driver: bridge
services:
  pac-authentication:
    build:
      context: "./src/authentication"
    container_name: "pac-authentication"
    ports:
      - "8001:8001"
    env_file:
      - ./envs/.env.test
    command: ["fastapi", "run", "./app/Authentication.py", "--port", "8001"]
    networks:
      - pac-network
  pac-challenges:
    build:
      context: "./src/challenges"
    container_name: "pac-challenges"
    ports:
      - "8002:8002"
    env_file:
      - ./envs/.env
    command: ["fastapi", "run", "./app/Challenges.py", "--port", "8002"]
    networks:
      - pac-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 2s
      retries: 5
  tester:
    build:
      context: "./tests/unit_tests"
    container_name: "tester"
    env_file:
      - ./envs/.env.test
    networks:
      - pac-network
    depends_on:
      - pac-authentication
